title: Light Of Science
email: contact@lightofscience.org.in
description: Light Of Science
baseurl: "/" 
url: "https://LightOfScience.org.in"
twitter_username: _LightOfScience
github_username:  LightOfScience

# Build settings
future: true
plugins:
  - jekyll-feed
  - octopress-paginate
  - jekyll-sitemap

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - gulpfile.js
  - CNAME
  - COPYING
  - README
  - package.json
  - package-lock.json

liquid:
  error_mode        : warn
  strict_filters    : false
  strict_variables  : false

collections_dir: collections
collections:
  front-page-carousel:
    output: false
  news:
    output: true
    permalink: /news/:year/:title/
  activities:
    output: true
    permalink: /activities/:year/:title/
  posts:
    output: true
    permalink: /blog/:year/:month/:title/
  publications:
    output: true
    permalink: /publications/:slug/
  prakriti:
    output: true
    permalink: /publications/prakriti/:title/
  breakthrough:
    output: true
    permalink: /publications/breakthrough/:title/



#paginate:
#  collection: posts news
#  per_page: 2
#  permalink: '/page:num/'
#  title_suffix: ' - page :num'
#  limit: false
#  reverse: true
