
backend:
  name: git-gateway
  branch: netlify-cms
  publish_mode: editorial_workflow

media_folder: "/media"

collections:
  - name: "front-carousel"
    label: "Front Page Carousel"
    folder: "collections/_front-page-carousel"
    media_folder: "/front-page/carousel"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", defaul: ""}
      - {label: "Image", name: "image", widget: "image", defaul: ""}
      - {label: "Body", name: "body", widget: "text", defaul: ""}
      - {label: "Link", name: "link", widget: "string"}

  - name : "news"
    label: "News"
    folder: "collections/_news"
    media_folder: "/news/{{fields.YYYY}}/{{slug}}/"
    create: true
    slug: "{{fields.YYYY}}-{{fields.MM}}-{{fields.DD}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post-news"}
      - {label: "Date", name: "DD", widget: "datetime", dateFormat: "DD", timeFormat:false, format: "DD"}
      - {label: "Month", name: "MM", widget: "datetime", dateFormat: "MM", timeFormat:false, format: "MM"}
      - {label: "Year", name: "YYYY", widget: "datetime", dateFormat: "YYYY", format: "YYYY"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image", default: ""}
      - {label: "Image Alt text", name: "image_alt", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Tags (separate by ',' of ' ')", name: "tags", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

