
backend:
  name: git-gateway
  branch: netlify-cms
  publish_mode: editorial_workflow

media_folder: "/media"

collections:
  - name: "front-carousel"
    label: "Front Page Carousel"
    folder: "collections/_front-page-carousel"
    media_folder: "/front-page/carousel"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string",  default: ""}
      - {label: "Image", name: "image", widget: "image", default: ""}
      - {label: "Body", name: "body", widget: "text", required: false, default: ""}
      - {label: "Link", name: "link", widget: "string", required: false, default: ""}

  - name : "news"
    label: "News"
    folder: "collections/_news"
    media_folder: "/news/{{fields.YYYY}}/{{slug}}/"
    create: true
    slug: "{{fields.YYYY}}-{{fields.MM}}-{{fields.DD}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post-news"}
      - {label: "Date", name: "DD", widget: "datetime", dateFormat: "DD", timeFormat: false, format: "DD"}
      - {label: "Month", name: "MM", widget: "datetime", dateFormat: "MM", timeFormat: false, format: "MM"}
      - {label: "Year", name: "YYYY", widget: "datetime", dateFormat: "YYYY", format: "YYYY"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image", default: ""}
      - {label: "Image Alt text", name: "image_alt", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Tags (separate by ',' or ' ')", name: "tags", widget: "string"}
      - {label: "Categories (separate by ',' or ' ')", name: "categories", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name : "blog"
    label: "Blog"
    folder: "collections/_posts"
    media_folder: "/blog/{{fields.YYYY}}/{{fields.MM}}/{{slug}}/"
    create: true
    slug: "{{fields.YYYY}}-{{fields.MM}}-{{fields.DD}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post-blog"}
      - {label: "Date", name: "DD", widget: "datetime", dateFormat: "DD", timeFormat: false, format: "DD"}
      - {label: "Month", name: "MM", widget: "datetime", dateFormat: "MM", timeFormat: false, format: "MM"}
      - {label: "Year", name: "YYYY", widget: "datetime", dateFormat: "YYYY", format: "YYYY"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image", default: ""}
      - {label: "Image Alt text", name: "image_alt", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Tags (separate by ',' or ' ')", name: "tags", widget: "string"}
      - {label: "Categories (separate by ',' or ' ')", name: "categories", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name : "activity"
    label: "Activities"
    folder: "collections/_activities"
    media_folder: "/activities/{{fields.YYYY}}/{{slug}}/"
    create: true
    slug: "{{fields.YYYY}}-{{fields.MM}}-{{fields.DD}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post-activity"}
      - {label: "Date", name: "DD", widget: "datetime", dateFormat: "DD", timeFormat: false, format: "DD"}
      - {label: "Month", name: "MM", widget: "datetime", dateFormat: "MM", timeFormat: false, format: "MM"}
      - {label: "Year", name: "YYYY", widget: "datetime", dateFormat: "YYYY", format: "YYYY"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image", default: "", allow_multiple: false}
      - {label: "Image Alt text", name: "image_alt", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Tags (separate by ',' or ' ')", name: "tags", widget: "string"}
      - {label: "Categories", name: "categories", widget: "select", multiple: true, options: [competition, seminar, campeign, press-release, BSS]}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Documents", name: "file", widget: "file", required: false}

  - name : "publication"
    label: "Publications (except Brekathrough and Prakriti)"
    folder: "collections/_publications"
    media_folder: "/publications/{{slug}}/"
    create: true
    slug: "{{fields.id}}-{{slug}}"
    fields:
      - {label: "ID", name: "id", widget: "number", valueType: int, step: 1, default: 0}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image", default: "", allow_multiple: false}
      - {label: "Image Alt text", name: "image_alt", widget: "string"}
      - {label: "Subtitle", name: "sub-title", widget: "string", required: false}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "E-commerce Link", name: "ecom-link", widget: "string", required: false}
      - {label: "Tags (separate by ',' or ' ')", name: "tags", widget: "string"}
      - {label: "Table of Content", name: "file", widget: "file", required: false}

  - name : "breakthrough-journal"
    label: "Breakthrough Journal"
    folder: "collections/_publications/_breakthrough"
    media_folder: "/publications/breakthrough/{{slug}}/"
    create: true
    slug: "{{fields.vol}}-{{fields.no}}-{{fields.YYYY}}-{{fields.MM}}"
    fields:
      - {label: "Vol.", name: "vol", widget: "number", valueType: int, default: 0}
      - {label: "No.", name: "no", widget: "number", valueType: int, default: 0}
      - {label: "Month", name: "MM", widget: "datetime", dateFormat: "MM", timeFormat: false, format: "MM"}
      - {label: "Year", name: "YYYY", widget: "datetime", dateFormat: "YYYY", format: "YYYY"}
      - {label: "Image", name: "image", widget: "image", default: "", allow_multiple: false}
      - {label: "Image Alt text", name: "image_alt", widget: "string"}
      - {label: "Subtitle", name: "sub-title", widget: "string", required: false}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "E-commerce Link", name: "ecom-link", widget: "string", required: false}
      - {label: "Tags (separate by ',' or ' ')", name: "tags", widget: "string"}
      - {label: "Table of Content", name: "file", widget: "file", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

#  - name : "prakriti-magazine"
#    label: "Prakriti Magazine"
#    folder: "collections/_publications/_prakriti"
#    media_folder: "/publications/prakriti/{{slug}}/"
#    create: true
#    slug: "{{fields.vol}}.{{fields.no}}-{{slug}}"
#    fields:
#      - {label: "Vol.", name: "vol", widget: "number", valueType: int, default: 0}
#      - {label: "No.", name: "no", widget: "number", valueType: int, default: 0}
#      - {label: "Month", name: "MM", widget: "datetime", dateFormat: "MM", timeFormat: false, format: "MM"}
#      - {label: "Year", name: "YYYY", widget: "datetime", dateFormat: "YYYY", format: "YYYY"}
#      - {label: "Image", name: "image", widget: "image", default: "", allow_multiple: false}
#      - {label: "Image Alt text", name: "image_alt", widget: "string"}
#      - {label: "Subtitle", name: "sub-title", widget: "string", required: false}
#      - {label: "Price", name: "price", widget: "number"}
#      - {label: "E-commerce Link", name: "ecom-link", widget: "string", required: false}
#      - {label: "Tags (separate by ',' or ' ')", name: "tags", widget: "string"}
#      - {label: "Table of Content", name: "file", widget: "file", required: false}
#      - {label: "Body", name: "body", widget: "markdown"}
#
#
#